SELECT YEAR(S.SALES_DATE)YEAR,
MONTH(S.SALES_DATE)MONTH,
I.GENDER,
COUNT(DISTINCT S.USER_ID)USERS
FROM USER_INFO I
JOIN ONLINE_SALE S ON I.USER_ID=S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3;